"use client";

import React, { useState, useMemo, useEffect } from 'react';
import { useSearchParams, useRouter, usePathname } from 'next/navigation';
import { Card, Input } from '@/components/ui';
import { AdPlaceholder } from '@/components/layout/AdPlaceholder';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend, BarChart, Bar } from 'recharts';
import { useLocalDatabase } from '@/hooks/useLocalDatabase';
import confetti from 'canvas-confetti';
import { EmbedCode } from '@/components/calculators/EmbedCode';
import { calculatorConfigs } from '@/data/calculatorConfigs';
import { useCurrency } from '@/contexts/CurrencyContext';
import { Tooltip as EducationalTooltip } from '@/components/ui/Tooltip';

const GLOSSARY_TERMS: Record<string, string> = {
  "APR": "Annual Percentage Rate: The yearly interest generated by a sum that's charged to borrowers or paid to investors.",
  "Principal": "The original sum of money borrowed in a loan or put into an investment.",
  "Amortization": "The process of spreading out a loan into a series of fixed payments over time.",
  "ROI": "Return on Investment: A performance measure used to evaluate the efficiency of an investment.",
  "Capital Gains": "The profit earned on the sale of an asset which has increased in value.",
  "Inflation": "The rate at which the general level of prices for goods and services is rising."
};

const formatLabelWithTooltip = (label: string, currencySymbol: string) => {
  let updatedLabel = label.replace('($)', `(${currencySymbol})`);
  const termFound = Object.keys(GLOSSARY_TERMS).find(term => updatedLabel.toLowerCase().includes(term.toLowerCase()));
  if (termFound) {
    const parts = updatedLabel.split(new RegExp(`(${termFound})`, 'i'));
    return (
      <>
        {parts.map((part, i) => 
          part.toLowerCase() === termFound.toLowerCase() ? (
            <EducationalTooltip key={i} content={GLOSSARY_TERMS[termFound]}>
              {part}
            </EducationalTooltip>
          ) : part
        )}
      </>
    );
  }
  return updatedLabel;
};

const CustomTooltip = ({ active, payload, label, formatCurrency }: any) => {
  if (active && payload && payload.length) {
    return (
      <div style={{ background: 'var(--card-bg)', padding: '1rem', border: '1px solid var(--secondary-accent)', borderRadius: '8px', boxShadow: 'var(--shadow-md)' }}>
        {label && <p style={{ margin: '0 0 0.5rem 0', fontWeight: 600, color: 'var(--text-muted)' }}>{label}</p>}
        {payload.map((entry: any, index: number) => (
          <p key={index} style={{ margin: '0.2rem 0', color: entry.color || 'var(--text-primary)', fontWeight: 600 }}>
            {entry.name}: {formatCurrency ? formatCurrency(Number(entry.value), 2) : `$${Number(entry.value).toLocaleString()}`}
          </p>
        ))}
      </div>
    );
  }
  return null;
};

export function UniversalCalculator({ config: configProp, slug }: { config?: any; slug?: string }) {
  // Resolve config: prefer the prop, otherwise look up by slug from the client-side import
  const config = configProp ?? (slug ? calculatorConfigs[slug] : null);
  const searchParams = useSearchParams();
  const router = useRouter();
  const pathname = usePathname();
  const { saveScenario } = useLocalDatabase();
  const { currency, formatCurrency } = useCurrency();

  if (!config) return <div style={{ padding: '2rem', color: 'var(--text-muted)' }}>Calculator not found.</div>;

  // Normalize inputs: the original configs use "default", the new mega-configs use "defaultValue"
  const normalizedInputs = (config.inputs || []).map((inp: any) => ({
    ...inp,
    default: inp.default ?? inp.defaultValue ?? 0,
  }));

  // Initialize state from URL params if they exist, otherwise fallback to defaults
  const initialData: Record<string, number> = {};
  normalizedInputs.forEach((input: any) => {
    const paramVal = searchParams.get(input.id);
    initialData[input.id] = paramVal !== null ? parseFloat(paramVal) : input.default;
  });

  const [formData, setFormData] = useState(initialData);
  const [isCopied, setIsCopied] = useState(false);
  const [isSaved, setIsSaved] = useState(false);

  const handleSaveScenario = () => {
    const slug = pathname.split('/').pop() || '';
    saveScenario(slug, config.name, formData);
    setIsSaved(true);
    confetti({
      particleCount: 100,
      spread: 70,
      origin: { y: 0.6 },
      colors: ['#AD9C8E', '#222222', '#FFFFFF']
    });
    setTimeout(() => setIsSaved(false), 2000);
  };

  const handleExportCSV = () => {
    const header = Object.keys(formData).join(',');
    const row = Object.values(formData).join(',');
    const csvContent = "data:text/csv;charset=utf-8," + header + "\n" + row;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${config.name.replace(/\s+/g, '_')}_Export.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Sync state to URL on change (debounced)
  useEffect(() => {
    const handler = setTimeout(() => {
      const params = new URLSearchParams(searchParams.toString());
      let changed = false;
      Object.keys(formData).forEach(key => {
        if (formData[key] !== initialData[key]) {
          params.set(key, formData[key].toString());
          changed = true;
        }
      });
      if (changed) {
        router.replace(`${pathname}?${params.toString()}`, { scroll: false });
      }
    }, 500);
    return () => clearTimeout(handler);
  }, [formData, pathname, router, searchParams]);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const [isFetchingPrice, setIsFetchingPrice] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  const fetchLiveCryptoPrice = async (coinId: string, inputId: string) => {
    setIsFetchingPrice(true);
    try {
      const res = await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=${coinId}&vs_currencies=usd`);
      const data = await res.json();
      if (data[coinId] && data[coinId].usd) {
        setFormData(prev => ({
          ...prev,
          [inputId]: data[coinId].usd
        }));
      }
    } catch (e) {
      console.error("Failed to fetch live price", e);
    }
    setIsFetchingPrice(false);
  };

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      // @ts-ignore
      const html2pdf = (await import('html2pdf.js')).default;
      const element = document.getElementById('pdf-export-container');
      if (element) {
        const opt = {
          margin: 0.5,
          filename: `${config.name.replace(/\s+/g, '_')}_Report.pdf`,
          image: { type: 'jpeg' as const, quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' as const }
        };
        await html2pdf().set(opt).from(element).save();
      }
    } catch (e) {
      console.error("Failed to generate PDF", e);
    }
    setIsGeneratingPDF(false);
  };

  const handleInputChange = (id: string, value: string) => {
    setFormData(prev => ({
      ...prev,
      [id]: parseFloat(value) || 0
    }));
  };

  const { chartData, summary, chartType } = useMemo(() => {
    // New mega-calculator: has a `calculate` function — run it directly on the client
    if (typeof config.calculate === 'function') {
      try {
        const result = config.calculate(formData);
        const rawSummary = (result.summary || []).map((s: any) => ({
          label: s.label,
          value: s.isCurrency === false
            ? String(s.value)
            : typeof s.value === 'number'
              ? formatCurrency(s.value, 2)
              : String(s.value)
        }));
        const rawChart = result.chartData || result.summary
          ?.map((s: any) => {
            const numericVal = typeof s.value === 'number' ? s.value : parseFloat(String(s.value).replace(/[^0-9.-]+/g,""));
            return { name: s.label, value: numericVal };
          })
          ?.filter((item: any) => !isNaN(item.value)) || [];
        
        return { chartData: rawChart, summary: rawSummary, chartType: 'bar' as const };
      } catch {
        return { chartData: [], summary: [{ label: 'Error', value: 'Calculation failed' }], chartType: 'bar' as const };
      }
    }

    if (config.engine === 'loan') {
      const p = formData.principal || 0;
      const r = (formData.rate || 0) / 100 / 12;
      const n = (formData.years || 0) * 12;
      
      let pmt = 0;
      if (r > 0 && n > 0) {
        pmt = p * (r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1);
      } else if (n > 0) {
        pmt = p / n;
      }

      const totalPaid = pmt * n;
      const totalInterest = totalPaid - p;

      const cData = [
        { name: 'Principal', value: p },
        { name: 'Total Interest', value: totalInterest }
      ];

      return {
        chartData: cData,
        chartType: 'pie',
        summary: [
          { label: 'Estimated Monthly Payment', value: formatCurrency(pmt, 2) },
          { label: 'Total Interest Paid', value: formatCurrency(totalInterest, 2) },
          { label: 'Total Cost of Loan', value: formatCurrency(totalPaid, 2) }
        ]
      };
    } 
    
    if (config.engine === 'compound') {
      const p = formData.principal || 0;
      const monthly = formData.monthly || 0;
      const rate = (formData.rate || 0) / 100;
      const years = formData.years || 0;

      const cData = [];
      let currentBalance = p;
      let totalContributed = p;

      for (let y = 0; y <= years; y++) {
        cData.push({
          year: `Year ${y}`,
          balance: currentBalance,
          contributions: totalContributed
        });
        currentBalance = currentBalance * (1 + rate) + (monthly * 12);
        totalContributed += (monthly * 12);
      }

      const totalInterest = cData[cData.length - 1].balance - cData[cData.length - 1].contributions;

      return {
        chartData: cData,
        chartType: 'area',
        summary: [
          { label: 'Final Balance', value: formatCurrency(cData[cData.length - 1].balance, 0) },
          { label: 'Total Contributions', value: formatCurrency(cData[cData.length - 1].contributions, 0) },
          { label: 'Total Interest Earned', value: formatCurrency(totalInterest, 0) }
        ]
      };
    }

    // Default Arithmetic Engine
    const v1 = formData.value1 || 0;
    const v2 = formData.value2 || 0;
    const result = v1 + (v1 * (v2 / 100));

    return {
      chartData: [
        { name: 'Base Value', value: v1 },
        { name: 'Variable', value: v2 }
      ],
      chartType: 'pie',
      summary: [
        { label: 'Primary Amount', value: formatCurrency(v1, 2) },
        { label: 'Calculated Output', value: formatCurrency(result, 2) }
      ]
    };

  }, [formData, config, formatCurrency]);

  const COLORS = ['var(--primary-accent)', 'var(--secondary-accent)'];

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', alignItems: 'start' }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
        <Card>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
            <h3 style={{ color: 'var(--primary-accent)' }}>Calculator Inputs</h3>
            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
              <button 
                onClick={handleExportCSV}
                style={{ padding: '0.25rem 0.75rem', fontSize: '0.8rem', background: '#10B981', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 600, color: '#FFFFFF', opacity: 0.9 }}
              >
                📊 Export CSV
              </button>
              <button 
                onClick={handleSaveScenario}
                style={{ padding: '0.25rem 0.75rem', fontSize: '0.8rem', background: 'var(--status-warning)', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 600, color: '#FFFFFF', opacity: 0.9 }}
              >
                {isSaved ? '✓ Saved!' : '💾 Save'}
              </button>
              <button 
                onClick={handleCopyLink}
                style={{ padding: '0.25rem 0.75rem', fontSize: '0.8rem', background: 'var(--secondary-background)', border: '1px solid var(--secondary-accent)', borderRadius: '4px', cursor: 'pointer', fontWeight: 600, color: 'var(--text-primary)' }}
              >
                {isCopied ? 'Copied!' : '🔗 Copy Link'}
              </button>
            </div>
          </div>
          {normalizedInputs.map((input: any) => (
            <div key={input.id} style={{ marginBottom: '1.5rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                <label style={{ fontWeight: 600, color: 'var(--text-primary)' }}>
                  {formatLabelWithTooltip(input.label, currency.symbol)}
                </label>
                {config.category === "Crypto & Web3" && input.label.toLowerCase().includes('price') && (
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <button onClick={() => fetchLiveCryptoPrice('bitcoin', input.id)} disabled={isFetchingPrice} style={{ fontSize: '0.7rem', padding: '0.2rem 0.5rem', background: '#F7931A', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>BTC</button>
                    <button onClick={() => fetchLiveCryptoPrice('ethereum', input.id)} disabled={isFetchingPrice} style={{ fontSize: '0.7rem', padding: '0.2rem 0.5rem', background: '#627EEA', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>ETH</button>
                    <button onClick={() => fetchLiveCryptoPrice('solana', input.id)} disabled={isFetchingPrice} style={{ fontSize: '0.7rem', padding: '0.2rem 0.5rem', background: '#14F195', color: '#111', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>SOL</button>
                  </div>
                )}
              </div>
              <input 
                type="number"
                value={formData[input.id]}
                onChange={(e) => handleInputChange(input.id, e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid var(--secondary-accent)',
                  background: 'var(--secondary-background)',
                  color: 'var(--text-primary)',
                  fontSize: '1rem',
                  marginBottom: '0.5rem'
                }}
              />
              <input 
                type="range"
                min={input.min ?? 0}
                max={input.max ?? ((input.defaultValue || input.default) ? (input.defaultValue || input.default) * 2 : 1000000)}
                step={input.step ?? (input.max && input.max <= 100 ? 0.1 : 1)}
                value={formData[input.id]}
                onChange={(e) => handleInputChange(input.id, e.target.value)}
                className="premium-slider"
                style={{
                  width: '100%',
                  cursor: 'pointer',
                  accentColor: 'var(--primary-accent)'
                }}
              />
            </div>
          ))}
        </Card>

        <Card style={{ background: 'var(--secondary-background)', border: '2px solid var(--primary-accent)' }}>
          <div id="pdf-export-container" style={{ padding: '0.5rem', background: 'var(--secondary-background)' }}>
            <h3 style={{ marginBottom: '1rem', color: 'var(--primary-accent)', textAlign: 'center' }}>{config.name} Report</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {summary.map((item: { label: string; value: string }, index: number) => (
                <div key={index} style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid var(--secondary-accent)', paddingBottom: '0.5rem' }}>
                  <span style={{ color: 'var(--text-muted)' }}>{item.label}</span>
                  <span style={{ fontWeight: 700, color: 'var(--text-primary)' }}>{item.value}</span>
                </div>
              ))}
            </div>
            
            {/* Shocking Math Snippet */}
            {config.name === "Ultimate Mortgage Calculator" && formData.interestRate > 0 && formData.loanTerm > 0 && (
               <div style={{ marginTop: '1.5rem', background: '#FEF2F2', padding: '1rem', borderRadius: '8px', borderLeft: '4px solid #EF4444' }}>
                 <p style={{ margin: 0, fontSize: '0.85rem', color: '#991B1B', fontWeight: 600 }}>
                   🤯 Shocking Fact: Over {formData.loanTerm} years, you will pay the bank more than {Math.round((formData.loanTerm * 12 * (summary.find((s: { label: string; value: string }) => s.label === "Monthly Payment")?.value ? parseFloat((summary.find((s: { label: string; value: string }) => s.label === "Monthly Payment")?.value || '0').replace(/[^0-9.-]+/g,"")) : 0) - formData.principalAmount) / formData.principalAmount * 100)}% of your original home value just in interest!
                 </p>
               </div>
            )}
            {config.name === "Compound Interest Calculator" && formData.years > 10 && (
               <div style={{ marginTop: '1.5rem', background: '#ECFDF5', padding: '1rem', borderRadius: '8px', borderLeft: '4px solid #10B981' }}>
                 <p style={{ margin: 0, fontSize: '0.85rem', color: '#065F46', fontWeight: 600 }}>
                   📈 Magic of Compounding: Without doing any extra work, compound interest generated more than {Math.round(((chartData as any[])[chartData.length-1]?.balance - ((chartData as any[])[chartData.length-1]?.contributions || 0)) / ((chartData as any[])[chartData.length-1]?.contributions || 1) * 100)}% of your total wealth. Time is your best asset!
                 </p>
               </div>
            )}
          </div>
        </Card>

        {/* Action Buttons for Results */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '0.5rem', marginTop: '1rem' }}>
          <button 
            onClick={handleExportCSV}
            style={{ padding: '0.75rem', fontSize: '0.9rem', background: 'var(--secondary-background)', border: '1px solid var(--secondary-accent)', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', transition: 'all 0.2s ease' }}
          >
            📊 CSV
          </button>
          <button 
            onClick={handleDownloadPDF}
            disabled={isGeneratingPDF}
            style={{ padding: '0.75rem', fontSize: '0.9rem', background: 'var(--secondary-background)', border: '1px solid var(--secondary-accent)', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', transition: 'all 0.2s ease' }}
          >
            {isGeneratingPDF ? '⏳ Generating...' : '📄 PDF'}
          </button>
          <button 
            onClick={() => window.print()}
            style={{ padding: '0.75rem', fontSize: '0.9rem', background: 'var(--primary-accent)', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, color: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', transition: 'all 0.2s ease' }}
          >
            🖨️ Print
          </button>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
        <Card>
          <h3 style={{ marginBottom: '1.5rem', color: 'var(--primary-accent)' }}>Visualization</h3>
          <div style={{ height: '300px' }}>
            <ResponsiveContainer width="100%" height="100%">
              {chartType === 'area' ? (
                <AreaChart data={chartData as any[]} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorBalance" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="var(--primary-accent)" stopOpacity={0.8}/>
                      <stop offset="95%" stopColor="var(--primary-accent)" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <XAxis dataKey={(chartData[0] as any)?.year ? "year" : "name"} stroke="var(--text-muted)" fontSize={12} tickMargin={10} />
                  <YAxis stroke="var(--text-muted)" fontSize={12} tickFormatter={(value) => formatCurrency(value, 0)} width={80} />
                  <Tooltip content={<CustomTooltip formatCurrency={formatCurrency} />} cursor={{ fill: 'rgba(173,156,142,0.1)' }} />
                  <Legend wrapperStyle={{ paddingTop: '20px' }} />
                  <Area type="monotone" dataKey="balance" name="Total Balance" stroke="var(--primary-accent)" fillOpacity={1} fill="url(#colorBalance)" />
                  <Area type="monotone" dataKey="contributions" name="Total Contributions" stroke="var(--text-muted)" fill="transparent" />
                </AreaChart>
              ) : chartType === 'bar' ? (
                <BarChart data={chartData as any[]} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                  <XAxis dataKey="name" stroke="var(--text-muted)" tick={{ fontSize: 11 }} />
                  <YAxis stroke="var(--text-muted)" tickFormatter={(value: any) => formatCurrency(value, 0)} />
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0" />
                  <Tooltip content={<CustomTooltip formatCurrency={formatCurrency} />} />
                  <Legend />
                  <Bar dataKey="value" name="Amount" fill="var(--primary-accent)" radius={[4,4,0,0]} />
                </BarChart>
              ) : (
                <PieChart>
                  <Pie data={chartData as any[]} cx="50%" cy="50%" innerRadius={60} outerRadius={100} paddingAngle={2} dataKey="value">
                    {chartData.map((entry: any, index: number) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip content={<CustomTooltip formatCurrency={formatCurrency} />} />
                  <Legend verticalAlign="bottom" height={36} />
                </PieChart>
              )}
            </ResponsiveContainer>
          </div>
        </Card>

            <div style={{ marginTop: '2rem' }}>
          <AdPlaceholder width="100%" height="90px" label="Advertisement Placeholder (AdSense / Display Network)" />
        </div>
      </div>
      
      <div style={{ gridColumn: '1 / -1' }}>
        <EmbedCode />
      </div>
    </div>
  );
}
